"""empty message

Revision ID: d688440af554
Revises: 5aeaee5f8a34
Create Date: 2022-06-12 23:18:18.994460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd688440af554'
down_revision = '5aeaee5f8a34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=300), nullable=True))
    op.add_column('Artist', sa.Column('find_venue', sa.Boolean(), nullable=False))
    op.add_column('Artist', sa.Column('seek_description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seek_description')
    op.drop_column('Artist', 'find_venue')
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
